# Generated by Django 2.2 on 2020-08-24 13:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntryForException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exception', models.TextField()),
                ('RequestUrl', models.TextField(default='')),
                ('UserAgent', models.TextField(default='')),
                ('IpAddress', models.TextField(default='')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('RoleId', models.UUIDField(primary_key=True, serialize=False)),
                ('ParentRoleId', models.UUIDField()),
                ('FullName', models.TextField(unique=True)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RolesRoutesMap',
            fields=[
                ('RoleRouteMapId', models.UUIDField(primary_key=True, serialize=False)),
                ('Status', models.BooleanField(default=False)),
                ('RoleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fk_RolesRoutesMap_RoleId', to='Models.Roles')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('RouteId', models.UUIDField(primary_key=True, serialize=False)),
                ('RouteName', models.TextField(unique=True)),
                ('DisplayName', models.TextField(unique=True)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Username', models.TextField(unique=True)),
                ('DisplayName', models.TextField()),
                ('Language', models.TextField()),
                ('Password', models.TextField()),
                ('Salt', models.TextField()),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersRolesMap',
            fields=[
                ('UserRoleMapId', models.UUIDField(primary_key=True, serialize=False)),
                ('Status', models.BooleanField()),
                ('RoleRouteMapId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fk_UsersRolesMap_RoleRouteMapId', to='Models.RolesRoutesMap')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fk_UsersRolesMap_UserId', to='Models.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('SessionId', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('Expiry', models.DateTimeField()),
                ('IsValid', models.BooleanField(default=True)),
                ('ChallengeCheck', models.TextField(default='')),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Models.User')),
            ],
        ),
        migrations.AddField(
            model_name='rolesroutesmap',
            name='RouteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fk_RolesRoutesMap_RouteId', to='Models.Routes'),
        ),
        migrations.AddConstraint(
            model_name='usersrolesmap',
            constraint=models.UniqueConstraint(fields=('UserId', 'RoleRouteMapId'), name='Uk_UsersRolesMap_UserId_RoleRouteMapId'),
        ),
        migrations.AddConstraint(
            model_name='rolesroutesmap',
            constraint=models.UniqueConstraint(fields=('RoleId', 'RouteId'), name='Uk_RolesRoutesMap_RoleId_RouteId'),
        ),
    ]
