# Generated by Django 2.2 on 2020-08-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('RoleId', models.UUIDField(primary_key=True, serialize=False)),
                ('ParentRoleId', models.UUIDField()),
                ('FullName', models.TextField(unique=True)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='RolesRoutesMap',
            fields=[
                ('RoleRouteMapId', models.UUIDField(primary_key=True, serialize=False)),
                ('Status', models.BooleanField(default=False)),
                ('RoleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fk_RolesRoutesMap_RoleId', to='Models.Roles')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('RouteId', models.UUIDField(primary_key=True, serialize=False)),
                ('RouteName', models.TextField(unique=True)),
                ('DisplayName', models.TextField(unique=True)),
                ('Status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.UUIDField(primary_key=True, serialize=False)),
                ('Username', models.TextField(unique=True)),
                ('DisplayName', models.TextField()),
                ('Language', models.TextField()),
                ('Password', models.TextField()),
                ('Salt', models.TextField()),
                ('Status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='UsersRolesMap',
            fields=[
                ('UserRoleMapId', models.UUIDField(primary_key=True, serialize=False)),
                ('Status', models.BooleanField()),
                ('RoleRouteMapId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fk_UsersRolesMap_RoleRouteMapId', to='Models.RolesRoutesMap')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fk_UsersRolesMap_UserId', to='Models.User')),
            ],
        ),
        migrations.AddField(
            model_name='rolesroutesmap',
            name='RouteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Fk_RolesRoutesMap_RouteId', to='Models.Routes'),
        ),
        migrations.AddConstraint(
            model_name='usersrolesmap',
            constraint=models.UniqueConstraint(fields=('UserId', 'RoleRouteMapId'), name='Uk_UsersRolesMap_UserId_RoleRouteMapId'),
        ),
        migrations.AddConstraint(
            model_name='rolesroutesmap',
            constraint=models.UniqueConstraint(fields=('RoleId', 'RouteId'), name='Uk_RolesRoutesMap_RoleId_RouteId'),
        ),
    ]
