# Generated by Django 2.2 on 2020-09-04 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('QueryId', models.UUIDField(db_column='QueryId', primary_key=True, serialize=False)),
                ('FullName', models.TextField(db_column='FullName', unique=True)),
                ('Description', models.TextField(db_column='Description')),
                ('Status', models.IntegerField(db_column='Status')),
            ],
            options={
                'db_table': '"Role"."Queries"',
            },
        ),
    ]
