# Generated by Django 2.2 on 2020-09-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_queries'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolesroutesmap',
            name='Operation',
            field=models.TextField(db_column='Operation', default=''),
            preserve_default=False,
        ),
    ]
