SUCCESS_RESPONSE_CODE = 200
METHOD_NOT_ALLOWED = 405
UNAUTHORIZED = 401
SUCCESS_RESPONSE_CREATED = 201
PAGE_NOT_FOUND = 404
INTERNAL_SERVER_ERROR = 500
BAD_REQUEST_CODE = 400

SUCCESS_MESSAGE = 'success'
FAILURE_MESSAGE = 'failure'